location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: uas_mapping
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.2-dev
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: firmware_1.13.2-deb
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
