#!/bin/sh
#
# @name NAKI II
#
# @type Octorotor Coaxial
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
#
# @maintainer Pavel Petracek <petrapa6@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

# param set MC_PITCH_P 2
# param set MC_PITCHRATE_P 0.12
# param set MC_PITCHRATE_I 0.05
# param set MC_PITCHRATE_D 0.006
# param set MC_PITCHRATE_MAX 180

# param set MC_ROLL_P 2
# param set MC_ROLLRATE_P 0.8
# param set MC_ROLLRATE_I 0.03
# param set MC_ROLLRATE_D 0.004
# param set MC_ROLLRATE_MAX 180

# param set MC_YAW_P 1
# param set MC_YAWRATE_P 0.05
# param set MC_YAWRATE_I 0.03
# param set MC_YAWRATE_D 0

# param set MPC_HOLD_MAX_XY 0.25
# param set MPC_THR_MIN 0.15
# param set MPC_Z_VEL_MAX_DN 2

param set-default MAV_TYPE 14

set PWM_OUT 12345678

set MIXER octo_cox_w
