#!/bin/sh
#
# @name DJI F330 SITL
#
# @type Quadcopter x
#
# @maintainer Petr Stibinger <stibipet@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 8000
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_LOAD_DROP 0.4

# param set MC_PITCH_P 2
# param set-default MC_PITCHRATE_P 0.01
# param set-default MC_PITCHRATE_I 0.01
# param set-default MC_PITCHRATE_D 0.002
# param set MC_PITCHRATE_MAX 180

# param set MC_ROLL_P 2
# param set-default MC_ROLLRATE_P 0.01
# param set-default MC_ROLLRATE_I 0.01
# param set-default MC_ROLLRATE_D 0.002
# param set MC_ROLLRATE_MAX 180

# param set MC_YAW_P 1
# param set MC_YAWRATE_P 0.05
# param set MC_YAWRATE_I 0.03
# param set MC_YAWRATE_D 0

# param set MPC_HOLD_MAX_XY 0.25
# param set MPC_THR_MIN 0.15
# param set MPC_Z_VEL_MAX_DN 2

set MIXER quad_x
