#!/bin/sh
#
# @name DJI F550 SITL
#
# @type Hexacopter x
#
# @maintainer Vojtech Spurny <vojtech.spurny@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

set MIXER hexa_x
